### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ibecir** [mcamovic1/Grupa-AMA#3]
1. ER dijagram bi trebao sacinjavati i AspNetUser klasu koja je bazna klasa za sve usere
2. Pogresna implementacija bridge patterna

**Comment by ibecir** [comment]
@ibecir TODO dodati probleme za patterne koji su koristeni

**Comment by ibecir** [comment]
Popraviti bridge pattern, ostali se na prvu cine dobro, vidjet cemo jos jednom prilikom odbrane

**Comment by mcamovic1** [comment]
@ibecir  Da li možete da provjerite da li je sada Bridge pattern u redu? Takođe, da li biste mogli da pogledate i task 10?

**Comment by ibecir** [comment]
Uredu je sad
